E:\mk64\ARMIPS\bin\mips64-elf-gcc -Wall -O1 -mtune=vr4300 -march=vr4300 -mabi=32 -fomit-frame-pointer -G0 -c "OverKart\OverKart.c" -o "OverKart\OverKart.o"
E:\mk64\ARMIPS\bin\mips64-elf-gcc -Wall -O1 -mtune=vr4300 -march=vr4300 -mabi=32 -fomit-frame-pointer -G0 -c "OverKart\CustomLevels.c" -o "OverKart\CustomLevels.o"
E:\mk64\ARMIPS\bin\mips64-elf-gcc -Wall -O1 -mtune=vr4300 -march=vr4300 -mabi=32 -fomit-frame-pointer -G0 -c "OverKart\MarioKartMenu.c" -o "OverKart\MarioKartMenu.o"
E:\mk64\ARMIPS\bin\mips64-elf-gcc -Wall -O1 -mtune=vr4300 -march=vr4300 -mabi=32 -fomit-frame-pointer -G0 -c "OverKart\MarioKartPractice.c" -o "OverKart\MarioKartPractice.o"
E:\mk64\ARMIPS\bin\mips64-elf-gcc -Wall -O1 -mtune=vr4300 -march=vr4300 -mabi=32 -fomit-frame-pointer -G0 -c "OverKart\MarioKartStats.c" -o "OverKart\MarioKartStats.o"
E:\mk64\ARMIPS\bin\mips64-elf-gcc -Wall -O1 -mtune=vr4300 -march=vr4300 -mabi=32 -fomit-frame-pointer -G0 -c "OverKart\MarioKartAI.c" -o "OverKart\MarioKartAI.o"
E:\mk64\ARMIPS\bin\armips "OverKart\PALOverKart3.asm"
E:\mk64\ARMIPS\bin\n64crc "OverKart\ROM\MOD - Mario Kart 64 (E) (V1.1) [!].z64"
